PACKAGE_NAME="liquidrust_hid"
PACKAGE_VERSION="0.2.2"

MAKE[0]="make KDIR=${kernel_source_dir}"

BUILT_MODULE_NAME[0]="liquidrust_hid"
BUILT_MODULE_LOCATION[0]="."
DEST_MODULE_LOCATION[0]="/kernel/drivers/hid"

AUTOINSTALL="yes"
